trigger:
  branches:
    include:
      - user/mani

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'crm-backend'
  registry: 'registry.nafabarter.com'
  fullImageName: '$(registry)/$(imageName)'
  tag: '$(Build.BuildId)'

steps:

- task: Docker@2
  displayName: 'Build and push $(imageName)'
  inputs:
    command: buildAndPush
    containerRegistry: 'nafa-registry'
    repository: '$(imageName)'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(tag)
    arguments: --no-cache

- script: |
    curl -X POST -k https://89.116.20.215:9443/api/stacks/webhooks/85d4b758-b6d8-44ce-8bd7-7c2384f37f01
  displayName: 'Trigger Portainer webhook deployment'
  condition: succeeded()