trigger:
  branches:
    include:
      - user/mani

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'crm-backend'
  registry: 'registry.nafabarter.com'
  fullImageName: '$(registry)/$(imageName)'
  tag: '$(Build.BuildId)'

steps:

- task: Docker@2
  displayName: 'Build and push $(imageName)'
  inputs:
    command: buildAndPush
    containerRegistry: 'nafa-registry'
    repository: '$(imageName)'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(tag)
    arguments: --no-cache

- script: |
    curl -X POST "https://89.116.20.215:9443/api/stacks/webhooks/436aad94-2603-40ed-bdcf-84fb642c8fcc?IMAGE_TAG=$(Build.BuildId)"
  displayName: 'Trigger Portainer webhook deployment'
  condition: succeeded()